In [10]:
data = """YOUR_DATA"""


# converting textual data into numbers¶

In [11]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

#### Tokenizer: This is a class from the tensorflow.keras.preprocessing.text module used for text preprocessing.

In [12]:
tokenizer = Tokenizer()

In [13]:
tokenizer.fit_on_texts([data])

In [14]:
tokenizer.word_index

{'her': 1,
 'and': 2,
 'to': 3,
 'the': 4,
 'a': 5,
 'of': 6,
 'she': 7,
 'in': 8,
 'for': 9,
 'was': 10,
 'with': 11,
 'tanisha': 12,
 'on': 13,
 'environmental': 14,
 'that': 15,
 'community': 16,
 'tanisha’s': 17,
 'through': 18,
 'often': 19,
 'academic': 20,
 'world': 21,
 'life': 22,
 'by': 23,
 'were': 24,
 'at': 25,
 'as': 26,
 'creative': 27,
 'their': 28,
 'professional': 29,
 'one': 30,
 'personal': 31,
 'journey': 32,
 'work': 33,
 'sustainable': 34,
 'lives': 35,
 'is': 36,
 'compassion': 37,
 'education': 38,
 'contributions': 39,
 'beyond': 40,
 'own': 41,
 'every': 42,
 'had': 43,
 'testament': 44,
 'commitment': 45,
 'impact': 46,
 'where': 47,
 'projects': 48,
 'pursuits': 49,
 'it': 50,
 'writing': 51,
 'significant': 52,
 'others': 53,
 'career': 54,
 'an': 55,
 'made': 56,
 'more': 57,
 'organization': 58,
 'all': 59,
 'story': 60,
 'ambition': 61,
 'creativity': 62,
 'deep': 63,
 'into': 64,
 'from': 65,
 'young': 66,
 'this': 67,
 'characterized': 68,
 'both': 69

In [15]:
len(tokenizer.word_index)

450

In [16]:
input_sequences = []
for sentence in data.split('\n'):
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

    for i in range(1,len(tokenized_sentence)):
        input_sequences.append(tokenized_sentence[:i+1])  #slicing

In [17]:
input_sequences

[[17, 60],
 [17, 60, 36],
 [17, 60, 36, 30],
 [17, 60, 36, 30, 6],
 [17, 60, 36, 30, 6, 130],
 [17, 60, 36, 30, 6, 130, 61],
 [17, 60, 36, 30, 6, 130, 61, 131],
 [17, 60, 36, 30, 6, 130, 61, 131, 62],
 [17, 60, 36, 30, 6, 130, 61, 131, 62, 2],
 [17, 60, 36, 30, 6, 130, 61, 131, 62, 2, 63],
 [17, 60, 36, 30, 6, 130, 61, 131, 62, 2, 63, 132],
 [17, 60, 36, 30, 6, 130, 61, 131, 62, 2, 63, 132, 37],
 [133, 64],
 [133, 64, 5],
 [133, 64, 5, 134],
 [133, 64, 5, 134, 15],
 [133, 64, 5, 134, 15, 135],
 [133, 64, 5, 134, 15, 135, 38],
 [133, 64, 5, 134, 15, 135, 38, 2],
 [133, 64, 5, 134, 15, 135, 38, 2, 31],
 [133, 64, 5, 134, 15, 135, 38, 2, 31, 136],
 [133, 64, 5, 134, 15, 135, 38, 2, 31, 136, 7],
 [133, 64, 5, 134, 15, 135, 38, 2, 31, 136, 7, 10],
 [133, 64, 5, 134, 15, 135, 38, 2, 31, 136, 7, 10, 137],
 [133, 64, 5, 134, 15, 135, 38, 2, 31, 136, 7, 10, 137, 65],
 [133, 64, 5, 134, 15, 135, 38, 2, 31, 136, 7, 10, 137, 65, 5],
 [133, 64, 5, 134, 15, 135, 38, 2, 31, 136, 7, 10, 137, 65, 5, 66

In [18]:
max_length = max([len(x) for x in input_sequences]) # har ek seq ka len nikala fir usme se max dhundha
max_length

31

### sari sequences k shape ko same krne k liye


In [20]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_length, padding='pre')

In [21]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  17,  60],
       [  0,   0,   0, ...,  17,  60,  36],
       [  0,   0,   0, ...,  60,  36,  30],
       ...,
       [  0,   0,   0, ...,   8,  59,  15],
       [  0,   0,   0, ...,  59,  15, 449],
       [  0,   0,   0, ...,  15, 449, 450]])

In [22]:
X = padded_input_sequences[:,:-1]  #saari ki saari rows but columns last vale ko chod k

In [23]:
X

array([[  0,   0,   0, ...,   0,   0,  17],
       [  0,   0,   0, ...,   0,  17,  60],
       [  0,   0,   0, ...,  17,  60,  36],
       ...,
       [  0,   0,   0, ...,  85,   8,  59],
       [  0,   0,   0, ...,   8,  59,  15],
       [  0,   0,   0, ...,  59,  15, 449]])

In [24]:
 Y = padded_input_sequences[:,-1]  #: : Select all rows. -1: Select the last element of each row (since -1 is a shorthand for the last element in Python indexing).

In [25]:
Y

array([ 60,  36,  30,   6, 130,  61, 131,  62,   2,  63, 132,  37,  64,
         5, 134,  15, 135,  38,   2,  31, 136,   7,  10, 137,  65,   5,
        66, 138,   3, 139,   1, 140,  11, 141,   2, 142, 143, 144, 145,
         4, 146,   9,   5,  22,  68,  23,  69,  31, 147,   2, 148,  39,
         3,   4,  16,  71,  70,  71,  24,  72,  11, 149,   2,   5,  73,
         9,  74,  10,   4, 150,   6, 151, 152, 153, 154,  75,   8, 155,
       156, 157,  40,   1,  41,  18,   4, 158,   6,   1, 159,  76, 160,
       161,   1, 162, 163,   9, 164, 165,   1,  11,  42,  77,   3,  78,
         2,  79, 166,   8,   1, 167, 168, 169,  25,   4,  80,   6,   1,
       170, 171,  19, 172,   1,   9,   1,  81,   2,  82, 173,  15,   7,
        43,   5,  83,  84,   3, 174, 175, 176,  11, 177,  85,  12,  86,
        18,   1,  20,  32,   1, 178,   9,  74, 179, 180, 181,   5, 182,
       183,   8,   4, 184, 185,  23,   4,  87,   4,  21, 186,   2,   4,
       187, 188,  15,  88, 189,  89, 190, 191, 192,   7, 193,   

In [26]:
X.shape

(938, 30)

In [27]:
Y.shape

(938,)

In [28]:
from tensorflow.keras.utils import to_categorical
Y= to_categorical(Y, num_classes=451)   #len(tokenizer.word_index)+1

In [29]:
Y.shape

(938, 451)

In [30]:
Y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [31]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [36]:
model = Sequential()
model.add(Embedding(451, 100, input_length=30))
model.add(LSTM(150))
model.add(Dense(451, activation='softmax'))

In [37]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [38]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 30, 100)           45100     
                                                                 
 lstm_1 (LSTM)               (None, 150)               150600    
                                                                 
 dense_1 (Dense)             (None, 451)               68101     
                                                                 
Total params: 263801 (1.01 MB)
Trainable params: 263801 (1.01 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [39]:
model.fit(X,Y,epochs=100)

Epoch 1/100


30/30 [==============================] - 7s 50ms/step - loss: 5.9518 - accuracy: 0.0384
Epoch 2/100
30/30 [==============================] - 1s 48ms/step - loss: 5.5537 - accuracy: 0.0480
Epoch 3/100
30/30 [==============================] - 1s 49ms/step - loss: 5.4558 - accuracy: 0.0501
Epoch 4/100
30/30 [==============================] - 1s 48ms/step - loss: 5.4232 - accuracy: 0.0490
Epoch 5/100
30/30 [==============================] - 1s 49ms/step - loss: 5.3819 - accuracy: 0.0736
Epoch 6/100
30/30 [==============================] - 2s 51ms/step - loss: 5.3201 - accuracy: 0.0704
Epoch 7/100
30/30 [==============================] - 1s 49ms/step - loss: 5.2291 - accuracy: 0.0704
Epoch 8/100
30/30 [==============================] - 1s 48ms/step - loss: 5.1092 - accuracy: 0.0704
Epoch 9/100
30/30 [==============================] - 1s 47ms/step - loss: 4.9720 - accuracy: 0.0949
Epoch 10/100
30/30 [==============================] - 2s 51ms/step - loss: 4.8328 - accuracy: 0.10

In [ ]:
import time
import numpy as np
text = "As Tanisha progressed"

for i in range(10):
    token_text = tokenizer.texts_to_sequences([text])[0]  
    padded_token_text = pad_sequences([token_text], maxlen=30, padding='pre')
    
    pos = np.argmax(model.predict(padded_token_text))

    for word, index in tokenizer.word_index.items():
        if index == pos:
            text = text + " " + word
            print(text)
            time.sleep(2)  

In [ ]:
#As Tanisha progressed through her academic journey, her passion for learning only intensified.